# Generated by Django 4.0.6 on 2022-08-05 06:37

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='AAA111', max_length=6, validators=[course.models.is_valid_code]),
            preserve_default=False,
        ),
    ]
