# Generated by Django 4.0.6 on 2022-08-05 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_course_archived_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'level': 200}, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
