# Generated by Django 4.0.6 on 2022-08-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='synopsis',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
