# Generated by Django 4.0.6 on 2022-08-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_description_course_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
